### ISSUE TITLE
出现bug了

### ISSUE THREAD

**Issue by 54binge** [luiing/StackViewLayout#1]
1.bug：取消自动滑动，然后手指向层叠位置位置滑动，正确效果是顶部增加，反复尝试顶部增加就会出现从顶部消失的现象，好像是滑过头了
2：adapter建议，StackAdapter中onCreateView把index暴露出来，以满足不同item的需求

**Comment by luiing** [comment]
感谢您的反馈。
1.第一个问题
顶层手势背向层叠：顶层滑出，下层上浮
顶层手势朝向层叠：顶层新加，其他下沉
手势方向根据按下时移动方向确定，一个完整动作通过滑动速度和距离判断，
满足才会顶层滑出或顶层新加，反之恢复之前的状态。
你上面的问题应该是恢复滑动前的状态了
2.第二个问题
此处没有支持多种布局公用（类似viewType）,数据绑定onBindView(View view, int index)有index
后续可以考虑支持viewType，返回index意义不大

**Comment by 54binge** [comment]
@luiing hi,我弄了个gif图，看最后一帧应该是出bug了吧
![video](https://user-images.githubusercontent.com/4814206/80474602-3b2c5d00-897a-11ea-8297-11199808d61b.gif)

**Comment by luiing** [comment]
看到了，滑动快会出现这问题，修复会加上日程

**Comment by 54binge** [comment]
辛苦了！
